services:

  fastapi-mongo:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-mongo-image
    container_name: fastapi-mongo
    environment:
      API_ENV: testing
    command: ["poetry", "run", "uvicorn", "main:get_app", "--host", "0.0.0.0", "--port", "8085", "--reload", "--log-level", "debug"]
    volumes:
      - .:/app
    ports:
      - "8085:8085"
    networks:
      - my-network

  mongo:
      image: mongo
      container_name: mongo-db
      ports:
          - "27017:27017"
      volumes:
          - './db:/data/db'
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 1234
      networks:
        - my-network

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
          ME_CONFIG_MONGODB_SERVER: mongo
          ME_CONFIG_MONGODB_PORT: 27017
      depends_on:
          - mongo
      ports:
        - "8081:8081"
      networks:
        - my-network

networks:
  my-network:
    driver: bridge